Djano_stuff/Adv_CBV/CBV/CBV/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view()),
    url(r'^basic_app/',include("basic_app.urls",namespace='basic_app'))
]

Djano_stuff/Adv_CBV/CBV/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'
urlpatterns = [
    url(r'^$',views.SchoolListView.as_view(),name='list'),
    url(r'(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name= 'detail'),
    url(r'^create/$',views.SchoolCreateView.as_view(),name = 'create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update')    


]

Djano_stuff/Adv_CBV/CBV/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs ={ 'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name="students",on_delete=None)

    def __str__(self):
        return self.name

Djano_stuff/Adv_CBV/CBV/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from . import models
# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'



class SchoolListView(ListView):
    context_object_name = "schools"
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = "school_detail"
    model = models.School
    template_name = 'basic_app/school_details.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

Djano_stuff/Adv_CBV/CBV/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <title>Base</title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'basic_app:list'%}">Schools</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
        <li><a class="navbar-link" href="#">Schools</a></li>
      </ul>
    </nav>
    <div class="container">
      {% block body_block%}
      {% endblock %}

    </div>
  </body>
</html>

Djano_stuff/Adv_CBV/CBV/templates/index.html
{% extends "base.html"%}
{% block body_block%}
  <div class="jumbotron">
    <h1>Home Page!</h1>
  </div>
{% endblock %}